name: Build for Mac

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Build Mac
        run: |
          flutter build macos --release --dart-define-from-file=pili_release.json

      - name: Prepare Upload
        run: |
          npm install --global create-dmg
          create-dmg --no-code-sign "cd build/macos/Build/Products/Release/PiliPlusX.app" .
        continue-on-error: true

      - name: Rename DMG
        run: mv PiliPlusX*.dmg PiliPlusX_macos_${{ env.version }}.dmg

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          prerelease: true
          files: |
            PiliPlusX_macos_${{ env.version }}.dmg

      - name: Upload macos release
        uses: actions/upload-artifact@v4
        with:
          name: macOS-release
          path: PiliPlusX_macos_*.dmg
